# Override pour production
replicaCount: 2
image:
  tag: "f50abd4" # Remplacé automatiquement par CI/CD
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
autoscaling:
  minReplicas: 2
  maxReplicas: 50
