# Override pour production
replicaCount: 2
image:
  tag: "f50abd4" # Remplacé automatiquement par CI/CD
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "4000m"
    memory: "4Gi"
autoscaling:
  minReplicas: 2
  maxReplicas: 50
