# Override pour production
replicaCount: 2
image:
  tag: "789ff1d" # Remplacé automatiquement par CI/CD
resources:
  requests:
    cpu: "1000m"
    memory: "1Gi"
  limits:
    cpu: "4000m"
    memory: "4Gi"
autoscaling:
  minReplicas: 2
  maxReplicas: 50
