apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: production
spec:
  provider: azure
  secretObjects:
  - secretName: app-secrets
    type: Opaque
    data:
    - objectName: postgresql-connection-string
      key: postgresql-connection-string
    - objectName: redis-connection-string
      key: redis-connection-string
    - objectName: postgres-db-password
      key: postgres-db-password
    - objectName: jwt-secret
      key: jwt-secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "7327c71d-48e0-4da1-92b1-d3df9c3b78a8" # Utiliser Workload Identity
    keyvaultName: kv-sedra5-mess-2
    tenantId: fbbc7131-e77d-4017-9de1-cb8ead937c1f
    objects: |
      array:
        - |
          objectName: postgresql-connection-string
          objectType: secret
        - |
          objectName: redis-connection-string
          objectType: secret
        - |
          objectName: postgres-db-password
          objectType: secret
        - |
          objectName: jwt-secret
          objectType: secret
