apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-ha-postgresql
  namespace: production
  labels:
    app: postgresql-ha-postgresql
spec:
  replicas: 1
  serviceName: postgresql-ha-postgresql-headless
  selector:
    matchLabels:
      app: postgresql-ha-postgresql
  template:
    metadata:
      labels:
        app: postgresql-ha-postgresql
        azure.workload.identity/use: "true"
    spec:
      containers:
      - name: postgresql
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-db-password
        - name: POSTGRES_DB
          value: "messenger"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        ports:
        - containerPort: 5432
          name: tcp-postgresql
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-keyvault-secrets"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: managed-premium
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-ha-pgpool
  namespace: production
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql-ha-postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-ha-postgresql
  namespace: production
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql-ha-postgresql
