apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: messenger-web-pdb
  namespace: production
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: messenger-web
