# Override pour production
replicaCount: 2
image:
  tag: "48fb89e" # Remplacé automatiquement par CI/CD
resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"
autoscaling:
  minReplicas: 2
  maxReplicas: 20
env:
  apiUrl: "https://api.messcrypt.com/api"
  signalrUrl: "https://api.messcrypt.com/hubs/chat"
