# Override pour production
replicaCount: 2
image:
  tag: "456aa36" # Remplacé automatiquement par CI/CD
resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"
autoscaling:
  minReplicas: 2
  maxReplicas: 20
