apiVersion: v1
kind: ConfigMap
metadata:
  name: messenger-api-config
  namespace: production
  labels:
    app: messenger-api
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
  ASPNETCORE_URLS: "http://+:8080"
  Cors__Origins__0: "https://messcrypt.com"
  Cors__Origins__1: "https://api.messcrypt.com"
