# Values utilisées pour le déploiement de Bitnami PostgreSQL en HA (PgPool + Repmgr)
# Commande: helm upgrade --install postgresql-ha bitnami/postgresql-ha -f infra/helm/postgresql-ha-values.yaml -n production

postgresql:
  replicaCount: 3
  database: messenger
  password: Sedra12345!
  repmgrPassword: repmgr_password
  postgresPassword: admin_password

pgpool:
  replicaCount: 2
  adminPassword: admin_password
