# Values utilisées pour le déploiement de Bitnami PostgreSQL en HA (PgPool + Repmgr)
# Commande: helm upgrade --install postgresql-ha bitnami/postgresql-ha -f infra/helm/postgresql-ha-values.yaml -n production

global:
  postgresql:
    auth:
      existingSecret: app-secrets

postgresql:
  replicaCount: 3
  database: messenger

pgpool:
  replicaCount: 2
  adminExistingSecret: app-secrets
